from PyQt5 import QtCore, QtGui, QtWidgets
import qrcode
import qrtools
class Ui_Form(object):
    def reader(self):
        qr = qrtools.QR()
        filename = self.textEdit_2.toPlainText()
        qr.decode(filename)
        self.textBrowser.setText(qr.data)
    def generator(self):
        qr = qrcode.QRCode(version=1, box_size=40,border=6)
        data = self.textEdit.toPlainText()
        qr.add_data(data)
        qr.make(fit=True)
        image = qr.make_image(fill_color="black", back_color= "white")
        image.save("data.png")
        self.label_3.setText("Operation completed successfully.")
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1432, 889)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(340, 730, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(510, 0, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(620, 40, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(40, 220, 591, 421))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.generate = QtWidgets.QPushButton(Form)
        self.generate.setGeometry(QtCore.QRect(280, 670, 95, 36))
        self.generate.clicked.connect(self.generator)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.generate.setFont(font)
        self.generate.setObjectName("generate")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(860, 240, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.read = QtWidgets.QPushButton(Form)
        self.read.setGeometry(QtCore.QRect(1060, 280, 95, 36))
        self.read.clicked.connect(self.reader)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.read.setFont(font)
        self.read.setObjectName("read")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(810, 350, 581, 441))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textBrowser.setObjectName("textBrowser")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(250, 100, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(1080, 90, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QRCode Generator and Reader by Aryaman"))
        self.label.setText(_translate("Form", "QRCode Generator and Reader"))
        self.label_2.setText(_translate("Form", "By Aryaman Sriram"))
        self.textEdit.setPlaceholderText(_translate("Form", "Enter your text here"))
        self.generate.setText(_translate("Form", "Generate"))
        self.textEdit_2.setPlaceholderText(_translate("Form", "Enter the filename or the whole path here:"))
        self.read.setText(_translate("Form", "Decode"))
        self.label_4.setText(_translate("Form", "Generator"))
        self.label_5.setText(_translate("Form", "Reader"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
